TechTreeMVCWebApplication/Areas/Admin/Controllers/CategoryController.cs
namespace TechTreeMVCWebApplication.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using System.Linq;
    using System.Threading.Tasks;
    using TechTreeMVCWebApplication.Data;
    using TechTreeMVCWebApplication.Entities;

    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context; 

        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Category
        public async Task<IActionResult> Index()
        {
            return View(await _context.Category.ToListAsync());
        }

        // GET: Admin/Category/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/Category/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,ThumbnailImagePath")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Category/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Admin/Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,ThumbnailImagePath")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Category/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Category.FindAsync(id);
            _context.Category.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.Id == id);
        }
    }
}

TechTreeMVCWebApplication/Controllers/UserAuthController.cs
namespace TechTreeMVCWebApplication.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using TechTreeMVCWebApplication.Data;
    using TechTreeMVCWebApplication.Entities;
    using TechTreeMVCWebApplication.Models;

    public class UserAuthController : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public UserAuthController(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _context = context;
        }


        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel model)
        {
            model.LoginInValid = "true";

            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: false);

                if (result.Succeeded)
                {
                    model.LoginInValid = string.Empty;
                }

                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                }
            }

            return PartialView("_UserLoginPartial", model);
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logоut(string returnUrl = null)
        {
            await _signInManager.SignOutAsync();

            if (returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }

            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> RegisterUser(RegistrationModel model)
        {
            model.RegistrationInValid = "true";

            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = model.Email,
                    Email = model.Email,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Address = model.Address,
                };

                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    model.RegistrationInValid = "";

                    await _signInManager.SignInAsync(user, isPersistent: false);

                    if (model.CategoryId != 0)
                    {
                        await AddCategoryToUser(user.Id, model.CategoryId);
                    }

                    return PartialView("_UserRegistrationPartial", model);
                }

                else
                {
                    AddErrorsToModelState(result);
                }
            }

            return PartialView("_UserRegistrationPartial", model);
        }

        private async Task AddCategoryToUser(string userId, int categoryId)
        {
            var userCategory = new UserCategory
            {
                UserId = userId,
                CategoryId = categoryId,
            };

            _context.UserCategory.Add(userCategory);

            await _context.SaveChangesAsync();
        }

        [AllowAnonymous]
        public async Task<bool> UserNameExist(string userName)
        {
            bool userNameExist = await _context.Users
                .AnyAsync(user => user.UserName.ToUpper() == userName.ToUpper());

            return userNameExist;
        }

        private void AddErrorsToModelState(IdentityResult result)
        {
            foreach (var error in result.Errors)
                ModelState.AddModelError(string.Empty, error.Description);
        }
    }
}

TechTreeMVCWebApplication/Views/Shared/_AdminMenuPartial.cshtml
@using TechTreeMVCWebApplication.Data
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> signInManager
@inject UserManager<ApplicationUser> userManager

@if (signInManager.IsSignedIn(User) && await userManager.IsInRoleAsync(userManager.GetUserAsync(User).Result, "Admin"))
{
    <li class="nav-item dropdown show">
        <a class="dropdown-toggle nav-link text-dark" href="#" data-bs-toggle="dropdown"><i class="fa-solid fa-screwdriver"></i>&nbsp;Admin</a>
        <div class="dropdown-menu">
            <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index"><i class="fas fa-box mr-2"></i>&nbsp;&nbsp;&nbsp;Categories</a>
            <a class="dropdown-item" asp-area="Admin" asp-controller="UsersToCategory" asp-action="Index"><i class="fas fa-users mr-2"></i>&nbsp;&nbsp;Users to Category</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-area="Admin" asp-controller="MediaType" asp-action="Index"><i class="fa-regular fa-folder-open"></i>&nbsp;&nbsp;&nbsp;Media Types</a>
        </div>
    </li>
}

else if(!signInManager.IsSignedIn(User))
{
    <li class="nav-item">
        <a class="nav-link text-dark" href="#Courses"><i class="fas fa-laptop-code mr-1 text-info"></i>Courses</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" href="#ContactUs"><i class="fas fa-phone-alt mr-1 text-info"></i>Contact Us</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" href="#AboutUs"><i class="fas fa-chalkboard-teacher mr-1 text-info"></i>About Us</a>
    </li>
}

TechTreeMVCWebApplication/Views/Shared/_AuthScriptsPartial.cshtml
<script src="~/js/UserLogin.js" asp-append-version="true"></script>
<script src="~/js/UserRegistration.js" asp-append-version="true"></script>
<script src="~/js/BootstrapAlerts.js" asp-append-version="true"></script>

TechTreeMVCWebApplication/Views/Shared/_DateScriptsPartial.cshtml
<script src="~/js/Datepicker.js"></script>
<script src="~/js/DateFunctions.js"></script>

TechTreeMVCWebApplication/Views/Shared/_DefaultHomePageContentPartial.cshtml
@model IEnumerable<Category>

<!--Hero Section-->
<div class="hero section">
    <img class="img-fluid" src="~/Images/HeroImage.jpeg">
    <div class="hero-heading">
        <h2 class="hero-heading-text">Learn Software Engineering at <strong>TechTree</strong></h2>
        <a id="HeroRegisterButton" class="btn btn-outline-info btn-lg text-light hero-register-button" data-bs-toggle="modal" data-bs-target="#userRegistrationModal">Register</a>
    </div>
</div>

<hr class="section-divider" />

<!--Courses Section-->
<div id="Courses" class="courses section">
    <h3 class="section-header"><i class="fas fa-laptop-code mr-2 text-info"></i>Courses</h3>
    @{
        const int itemsPerRow = 4;

        var count = Model.Count() / itemsPerRow;
        var catList = new List<Category>();

    }
    @for (int i = 0; i <= count; i++)
    {
        catList = Model.Skip(i * itemsPerRow).Take(itemsPerRow).ToList();

        <partial name="_DisplayCardRowPartial" model="catList" />

    }
</div>

<hr class="section-divider" />

<!--Contact Us Section-->

<div id="ContactUs" class="contact-us section">
    <h3 class="col-md-5 section-header"><i class="fas fa-phone-alt mr-2 text-info"></i>Contact Us</h3>
    <div class="col-md-5">
        Email us any questions or inquiries or call 518-387-9999. We would be happy to answer your questions and set up a meeting with you.
    </div>
    <div class="mt-3">
        <div class="col-md-8">
            <form>
                <input type="hidden" />
                <div class="form-group">
                    <label for="Name" class="control-label">Name: </label>
                    <input id="Name" class="form-control" />

                </div>
                <div class="form-group">
                    <label for="Email" class="control-label">Email: </label>
                    <input id="Email" class="form-control" />

                </div>
                <div class="form-group">
                    <label for="Subject" class="control-label">Subject: </label>
                    <input id="Subject" class="form-control" />

                </div>
                <div class="form-group">
                    <label for="MessageBody" class="control-label">Message: </label>
                    <textarea id="Messagebody" cols="30" rows="10" class="form-control"></textarea>

                </div>
                <div class="form-group d-flex">
                    <input type="button" value="Send Email" class="btn btn-outline-info ml-auto" />
                </div>
            </form>
        </div>
    </div>
</div>
<hr class="section-divider" />

<!--About Us Section-->

<div id="AboutUs" class="about-us section">
    <h3 class="col-md-5 section-header"><i class="fas fa-chalkboard-teacher mr-2 text-info"></i>About Us</h3>
    <div class="mt-3 mb-5">
        <div class="col-md-5">
            <p>
                <strong>TechTree</strong> provides articles and courses on programming topics. We started in 1998 and continue to provide high quality Tech content to our members.
            </p>
        </div>
    </div>
</div>

TechTreeMVCWebApplication/Views/Shared/_DisplayCardRowPartial.cshtml
@model IEnumerable<Category>

@if (Model.Count() > 0)
{
    <div class="row mt-3">
        @foreach (Category item in Model)
        {
            <div class="col-md-3 mt-3">

                @* 2. data for hidden input field for Home screen, section "Cources" list of cards categoryId *@
                <a href="#" class="RegisterLink text-dark" data-categoryId="@item.Id">
                    <div class="card">
                        <img class="img-thumbnail" src="@item.ThumbnailImagePath" alt="@item.Title">
                        <div class="card-body">
                            <h5 class="card-title">@item.Title</h5>
                            <p class="card-text">@item.Description</p>
                        </div>
                    </div>
                </a>
            </div>
        }
    </div>
}

TechTreeMVCWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TechTree</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TechTreeMVCWebApplication.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/lib/jquery-ui-1.13.1.custom/jquery-ui.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/images/TechTreeLogo.jpeg" height="35"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home mr-1 text-info"></i>&nbsp;Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li> *@
                        <partial name="_AdminMenuPartial" />
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TechTreeMVCWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-ui-1.13.1.custom/jquery-ui.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TechTreeMVCWebApplication/Views/Shared/_UserLoginPartial.cshtml
<!-- Button trigger modal -->
@*<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>*@

@model TechTreeMVCWebApplication.Models.LoginModel


<!-- Modal -->

  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Login</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <form id="userLoginForm" asp-controller="UserAuth" asp-action="Login">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="LoginInValid">
                    <div class="form-group row">
                        <label asp-for="Email" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="Email" placeholder="Email Address" class="form-control">
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Password" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="Password" placeholder="Password" class="form-control">
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group-row">
                        <div class="col-md-8 offset-md-4">
                            <div class="form-check">
                                <input asp-for="RememberMe" class="form-check-input">
                                <label asp-for="RememberMe" class="form-check-label"></label>
                            </div>
                        </div>
                    </div>
                </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" id="login" name="login" class="btn btn-primary">Login</button>
      </div>
    </div>
  </div>

TechTreeMVCWebApplication/Views/Shared/_UserRegistrationPartial.cshtml
@model TechTreeMVCWebApplication.Models.RegistrationModel

<!-- Modal -->

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Register</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
             <div id="alert_placeholder_register">
                </div>
            <form id="userRegistrationForm" asp-controller="UserAuth" asp-action="Login">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <input type="hidden" asp-for="RegistrationInValid" />
                @* 2. add hidden input field for Home screen, section "Cources" list of cards *@
                <input type="hidden" asp-for="CategoryId" />

                <div class="form-group row">
                    <label asp-for="Email" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Email" placeholder="Email Address" class="form-control">
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Password" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Password" placeholder="Password" class="form-control">
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="ConfirmPassword" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="ConfirmPassword" placeholder="Confirm Password" class="form-control">
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                        <label asp-for="FirstName" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="FirstName" placeholder="First Name" class="form-control">
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="LastName" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="LastName" placeholder="Last Name" class="form-control">
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                    </div>
                <div class="form-group row">
                    <label asp-for="Address" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Address" placeholder="Address" class="form-control">
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <div class="form-check">
                            <input asp-for="AcceptUserAgreement" class="form-check-input">
                            <label asp-for="AcceptUserAgreement" class="form-check-label">I accept the <a href="#">Terms of Use</a> and <a href="#">Privacy Policy</a></label>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" name="register" class="btn btn-primary">Register</button>
        </div>
    </div>
</div>