TechTreeMVCWebApplication/Controllers/CategoriesToUserController.cs
namespace TechTreeMVCWebApplication.Controllers
{
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using System;
    using TechTreeMVCWebApplication.Data;
    using TechTreeMVCWebApplication.Entities;
    using TechTreeMVCWebApplication.Models;

    public class CategoriesToUserController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IDataFunctions _dataFunctions;

        public CategoriesToUserController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IDataFunctions dataFunctions)
        {
            this._context = context;
            this._userManager = userManager;
            this._dataFunctions = dataFunctions;
        }

        public async Task<IActionResult> Index()
        {
            var model = new CategoriesToUserModel();

            model.Categories = await GetCategoriesThatHaveContent();

            var userId = _userManager.GetUserAsync(User).Result.Id;

            model.CategoriesSelected = await GetCategoriesSavedToUser(userId);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(string[] categoriesSelected)
        {
            var userId = _userManager.GetUserAsync(User).Result?.Id;

            List<UserCategory> userCategoriesToDelete = await GetCategoriesToDeleteForUser(userId);
            List<UserCategory> userCategoriesToAdd = GetCategoriesToAddForUser(categoriesSelected, userId);

            await _dataFunctions.UpdateUserCategoryEntityAsync(userCategoriesToDelete, userCategoriesToAdd);

            return RedirectToAction("Index", "Home");
        }

        private async Task<List<Category>> GetCategoriesSavedToUser(string userId)
        {
            var categoriesCurrentlySavedForUser = await (from userCategory in _context.UserCategory
                                                         where userCategory.UserId == userId
                                                         select new Category
                                                         {
                                                             Id = userCategory.CategoryId,
                                                         })
                                                         .ToListAsync();

            return categoriesCurrentlySavedForUser;
        }

        private async Task<List<Category>> GetCategoriesThatHaveContent()
        {
            var categoriesThatHaveContent = await (from category in _context.Category
                                                   join categoryItem in _context.CategoryItem
                                                   on category.Id equals categoryItem.CategoryId
                                                   join content in _context.Content
                                                   on categoryItem.Id equals content.CategoryItem.Id
                                                   select new Category
                                                   {
                                                       Id = category.Id,
                                                       Title = category.Title,
                                                       Description = category.Description
                                                   }).Distinct().ToListAsync();

            return categoriesThatHaveContent;
        }

        private async Task<List<UserCategory>> GetCategoriesToDeleteForUser(string userId)
        {
            var categoriesToDelete = await (from userCat in _context.UserCategory
                                            where userCat.UserId == userId
                                            select new UserCategory
                                            {
                                                Id = userCat.Id,
                                                CategoryId = userCat.CategoryId,
                                                UserId = userId
                                            }).ToListAsync();

            return categoriesToDelete;
        }

        private List<UserCategory> GetCategoriesToAddForUser(string[] categoriesSelected, string userId)
        {
            var categoriesToAdd = (from categoryId in categoriesSelected
                                   select new UserCategory
                                   {
                                       UserId = userId,
                                       CategoryId = int.Parse(categoryId)
                                   }).ToList();

            return categoriesToAdd;

        }
    }
}

TechTreeMVCWebApplication/Controllers/ContentController.cs
namespace TechTreeMVCWebApplication.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using TechTreeMVCWebApplication.Data;
    using TechTreeMVCWebApplication.Entities;

    public class ContentController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContentController(ApplicationDbContext context)
        {
            this._context = context;
        }

        public async Task<IActionResult> Index(int categoryItemId)
        {
            var content = await (from item in _context.Content
                                 where item.CategoryItem.Id == categoryItemId
                                 select new Content
                                 {
                                     Title= item.Title,
                                     VideoLink= item.VideoLink,
                                     HTMLContent= item.HTMLContent,
                                 })
                                 .FirstOrDefaultAsync();

            return View(content);
        }
    }
}

TechTreeMVCWebApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TechTreeMVCWebApplication.Data;
using TechTreeMVCWebApplication.Entities;
using TechTreeMVCWebApplication.Models;

namespace TechTreeMVCWebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _logger = logger;
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<CategoryItemDetailsModel> categoryItemDetailsModels = null;
            IEnumerable<GroupedCategoryItemsByCategoryModel> groupedCategoryItemsByCategoryModels = null;

            CategoryDetailsModel categoryDetailsModel = new CategoryDetailsModel();

            if (_signInManager.IsSignedIn(User))
            {
                var user = await _userManager.GetUserAsync(User);

                if (user != null)
                {
                    categoryItemDetailsModels = await GetCategoryItemDetailsForUser(user.Id);
                    groupedCategoryItemsByCategoryModels = GetGroupedCategoryItemsByCategory(categoryItemDetailsModels);

                    categoryDetailsModel.GroupedCategoryItemsByCategoryModels = groupedCategoryItemsByCategoryModels;

                }

            }
            else
            {
                var categories = await GetCategoriesThatHaveContent();

                categoryDetailsModel.Categories = categories;

            }

            return View(categoryDetailsModel);
        }

        private async Task<List<Category>> GetCategoriesThatHaveContent()
        {
            var categoriesWithContent = await (from category in _context.Category
                                               join categoryItem in _context.CategoryItem
                                               on category.Id equals categoryItem.CategoryId
                                               join content in _context.Content
                                               on categoryItem.Id equals content.CategoryItem.Id
                                               select new Category
                                               {
                                                   Id = category.Id,
                                                   Title = category.Title,
                                                   Description = category.Description,
                                                   ThumbnailImagePath = category.ThumbnailImagePath
                                               }).Distinct().ToListAsync();

            return categoriesWithContent;

        }

        private IEnumerable<GroupedCategoryItemsByCategoryModel> GetGroupedCategoryItemsByCategory(IEnumerable<CategoryItemDetailsModel> categoryItemDetailsModels)
        {
            return from item in categoryItemDetailsModels
                   group item by item.CategoryId into g
                   select new GroupedCategoryItemsByCategoryModel
                   {
                       Id = g.Key,
                       Title = g.Select(c => c.CategoryTitle).FirstOrDefault(),
                       Items = g
                   };
        }

        private async Task<IEnumerable<CategoryItemDetailsModel>> GetCategoryItemDetailsForUser(string userId)
        {
            return await (from catItem in _context.CategoryItem
                          join category in _context.Category
                          on catItem.CategoryId equals category.Id
                          join content in _context.Content
                          on catItem.Id equals content.CategoryItem.Id
                          join userCat in _context.UserCategory
                          on category.Id equals userCat.CategoryId
                          join mediaType in _context.MediaType
                          on catItem.MediaTypeId equals mediaType.Id
                          where userCat.UserId == userId
                          select new CategoryItemDetailsModel
                          {
                              CategoryId = category.Id,
                              CategoryTitle = category.Title,
                              CategoryItemId = catItem.Id,
                              CategoryItemTitle = catItem.Title,
                              CategoryItemDescription = catItem.Description,
                              MediaImagePath = mediaType.ThumbnailImagePath
                          }).ToListAsync();
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TechTreeMVCWebApplication/Views/Home/Index.cshtml
@model CategoryDetailsModel

@inject SignInManager<ApplicationUser> SignInManager

@{
    ViewData["Title"] = "Home Page";
}

@if (Model.GroupedCategoryItemsByCategoryModels != null)
{
     <div class="row">
        <div class="col-md-6">
            <h2>Your Courses</h2>
        </div>
        <div class="col-md-6 text-right">
            <a asp-controller="CategoriesToUser" asp-action="Index" class="btn btn-outline-dark">Choose Courses</a>
        </div>
    </div>

    @if (Model.GroupedCategoryItemsByCategoryModels.Count() > 0)
    {

        <div class="row mt-3">
            <div class="col-md-12">

                @foreach (var cat in Model.GroupedCategoryItemsByCategoryModels)
                {
                    <div class="card mt-2">
                        <h4 class="card-header text-secondary bg-white" style="cursor:pointer" data-bs-toggle="collapse" data-bs-target="#collapse_@cat.Id" aria-expanded="false" aria-controls="collapse_@cat.Id">
                            @cat.Title
                        </h4>
                        <div id="collapse_@cat.Id" class="collapse" aria-expanded="false" aria-controls="collapse_@cat.Id">
                            <hr />
                            @foreach (var item in cat.Items)
                            {
                                <div class="mt-2">
                                    <img src="@item.MediaImagePath" width="100" height="100" class="img-thumbnail float-left mr-2" />
                                    <h5 class="card-title mt-2">
                                        <a class="text-dark" asp-controller="Content" asp-action="Index" asp-route-CategoryItemId="@item.CategoryItemId">@item.CategoryItemTitle</a>
                                    </h5>
                                    <p class="card-text text-dark mt-2">
                                        @item.CategoryItemDescription
                                    </p>
                                </div>
                            }
                        </div>
                    </div>
                }

            </div>
        </div>
    }
    else
    {
        <h4 class="mt-2 text-warning">You are currently not matched with any courses</h4>

    }
}

else
{
    <partial name="_DefaultHomePageContentPartial" model="@Model.Categories" />

}

@*  &&   InvalidOperationException: The model item passed into the ViewDataDictionary is of type
    'TechTreeMVCWebApplication.Models.CategoryDetailsModel',
    but this ViewDataDictionary instance requires a model item of type 'TechTreeMVCWebApplication.Models.LoginModel'.
    _UserLoginPartial and _UserRegistrationPartial
*@
<div class="modal fade" id="userLoginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <partial name="_UserLoginPartial" model="new LoginModel
        {
            Email = String.Empty,
            Password = String.Empty,
            RememberMe = false
        }" />
</div>
<div class="modal fade" id="userRegistrationModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <partial name="_UserRegistrationPartial" model="new RegistrationModel
        {
            Email = String.Empty,
            Password = String.Empty,
            ConfirmPassword = String.Empty,
            FirstName = String.Empty,
            LastName = String.Empty,
            Address = String.Empty,
            AcceptUserAgreement = false
        }" />
</div>


@section Scripts{

    @{
        await Html.RenderPartialAsync("_AuthScriptsPartial");
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}